[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "httk2"
# While httk2 is in prerelease it doesn't follow semver (or more exactly,
# it follows semver 0.* semantics, where the non-major versions do not need to adhere to semver).
# Its minor version should always stay 0, and only the patch-level be increased.
version = "2.0.2"
description = "The high-throughput toolkit (httk₂) for materials science"
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.12"
authors = [{ name = "Rickard Armiento", email = "rickard-gpg@armiento.net" }]
dependencies = [
  "httk-core[default]>=2.0.2,<3",
  "httk-atomistic[default]>=0.2.0,<1",
  "httk-store[default]>=0.2.0,<1",
  "httk-serve[default]>=0.2.0,<1",
  "httk-analyse[default]>=0.1.0,<1",
  "httk-workflow[default]>=0.2.0,<1",
]
keywords = [
  "Materials Discovery",
  "Materials Informatics",
  "Materials Science",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Physics",
]

[project.optional-dependencies]
default = []
release = [
  "build>=1.2",
  "twine>=6.0",
]

[project.urls]
Homepage = "https://httk.org"
Documentation = "https://docs.httk.org"
Repository = "https://github.com/httk/httk2"
Issues = "https://github.com/httk/httk2/issues"

[tool.setuptools]
packages = []
